export const PARTNER_ORGANIZATIONS = [
  'CENTER FOR HEALTH, HUMAN RIGHTS AND DEVELOPMENT (CEHURD)',
  'CENTRE FOR COMMUNITY LAW',
  'CENTRE FOR WOMEN JUSTICE UGANDA (CWJU)',
  'COSWA',
  'DUMAIC GLOBAL HEALTH',
  'FEMME FORTE',
  'ISLAMIC WOMEN\'S INITIATIVE FOR JUSTICE LAW AND PEACE (IWILAP)',
  'KELIN',
  'LAWYERS ALERT',
  'LEAN ON ME FOUNDATION',
  'NIFIN\'AKANGA',
  'SPRINGS PUBLIC INTEREST HUB',
  'THE AFRICAN INSTITUTE FOR INVESTIGATIVE JOURNALISM (AIIJ)',
  'UBUNTU JUSTICE CENTER',
  'UBUNTU YOUTH ORGANIZATION',
  'VISION SPRING INITIATIVES',
  'VITAL RIGHTS FOUNDATION',
  'WOMEN WITH A MISSION',
  'WOMEN\'S ACTION GROUP',
  'WSLA',
];

export const OTHER_ORGANIZATION_VALUE = 'Other';

export const RESTRICTED_ORGANIZATIONS = PARTNER_ORGANIZATIONS;
